export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const DISMISS_LOGIN_FAIL = 'DISMISS_LOGIN_FAIL';
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const TOO_MANY_FAILED_LOGINS = 'TOO_MANY_FAILED_LOGINS';
