export const PASSWORD_FORGOT_SUCCESS = 'PASSWORD_FORGOT_SUCCESS';
export const PASSWORD_FORGOT_FAIL = 'PASSWORD_FORGOT_FAIL';
export const PASSWORD_FORGOT_NOT_FOUND = 'PASSWORD_FORGOT_NOT_FOUND';
export const PASSWORD_FORGOT_TOO_MANY_ATTEMPTS = 'PASSWORD_FORGOT_TOO_MANY_ATTEMPTS';
